update AUR packages

diff --git a/elasticsearch/PKGBUILD b/elasticsearch/PKGBUILD
--- a/elasticsearch/PKGBUILD
+++ b/elasticsearch/PKGBUILD
@@ -1,14 +1,14 @@
 # Maintainer:  HLFH <gaspard@dhautefeuille.eu>
 
 pkgname=elasticsearch
-pkgver=9.2.0
-pkgrel=1
+pkgver=9.2.1
+pkgrel=2
 pkgdesc="Free and Open, Distributed, RESTful Search Engine"
 arch=('aarch64' 'x86_64')
 url="https://www.elastic.co/elasticsearch/"
 license=('custom:Elastic-2.0')
-depends=('java-runtime' 'libxml2')
-makedepends=('jdk17-openjdk')
+depends=('jdk21-openjdk' 'libxml2')
+makedepends=()
 provides=("elasticsearch=$pkgver")
 conflicts=('elasticsearch7' 'elasticsearch-bin')
 source=(
@@ -22,7 +22,7 @@ source=(
   elasticsearch-tmpfile.conf
   elasticsearch.default
 )
-b2sums=('7427947459f05b59f252cb3f4b194a8c3625b5592bb13f151ebb9a679eeef0ae49d4384b78b3082ea222557b646cf2abc356231ce3eb0b5dfb98c8dc0ee80e4f'
+b2sums=('1ca543b66093cc7417e28ee6d235307b1d218de40e297b604fea0108c35a1857171424c46cc9c223bcde9610e04e902e7714532c7322efd0bb63b7e04de6d249'
         '76e4098c4f2c0656e70590997ada2e489c53b61386fb92524ac34e09b7fd43b511e2305047754bba29883d388fec4855dd8fc429e0e3aa93068ab671b6bd1a79'
         '9b74e7ae392132056ab5e8a9e2637d71564fe736d10c16e07395878c4ef0a5498147d8a5b7a28dac6ef3722bc525bb8a57b01f9e185613c46c4f34f3a69990c8'
         '48a332da75e1d8c7624a5948c4b145ad6ec6aca7ed2da31802920fa99490cc99a354e06d635b8937217404bcb99302f8d95b7af99d6af8e3227e39cdb80fa3cd'
@@ -39,9 +39,9 @@ backup=('etc/elasticsearch/elasticsearch.yml'
 
 build() {
   cd $pkgname-$pkgver
-  echo "Building using java-17-openjdk..."
+  echo "Building using java-21-openjdk..."
   # For now as jdk-openjdk upgraded to JDK21 experiencing warnings treated as errors.
-  export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
+  export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
   ./gradlew --no-daemon :modules:systemd:assemble
   ./gradlew --no-daemon :distribution:archives:linux-tar:assemble
 }
@@ -71,10 +71,12 @@ package() {
   ln -s /etc/elasticsearch "$pkgdir"/usr/share/elasticsearch/config
   ln -s /var/log/elasticsearch "$pkgdir"/usr/share/elasticsearch/logs
 
-  # Dynamically determine what version jdk-openjdk provides and symlink it.
-  jdk_openjdk_version=$(pacman -Ql java-runtime | grep -Pom1 '/usr/lib/jvm/java-[0-9]+-openjdk/')
-  [ -z "${jdk_openjdk_version}" ] && echo "Unable to determine jdk-openjdk version automatically" && exit 1
-  ln -s "${jdk_openjdk_version}" "$pkgdir"/usr/share/elasticsearch/jdk
+  ## Dynamically determine what version jdk-openjdk provides and symlink it.
+  # Good automation attempt but cannot be used. Elasticsearch falls behind java updates too often for a rolling release platform.
+  #jdk_openjdk_version=$(pacman -Ql java-runtime | grep -Pom1 '/usr/lib/jvm/java-[0-9]+-openjdk/')
+  #[ -z "${jdk_openjdk_version}" ] && echo "Unable to determine jdk-openjdk version automatically" && exit 1
+  #ln -s "${jdk_openjdk_version}" "$pkgdir"/usr/share/elasticsearch/jdk
+  ln -s "/usr/lib/jvm/java-21-openjdk" "$pkgdir"/usr/share/elasticsearch/jdk
 
   install -Dm644 "$srcdir"/elasticsearch.service "$pkgdir"/usr/lib/systemd/system/elasticsearch.service
   install -Dm644 "$srcdir"/elasticsearch@.service "$pkgdir"/usr/lib/systemd/system/elasticsearch@.service
